# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/user_const.xdc

# Block Designs: bd/zed_base/zed_base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base || ORIG_REF_NAME==zed_base}]

# IP: bd/zed_base/ip/zed_base_axi_gpio_0_0/zed_base_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_0_0 || ORIG_REF_NAME==zed_base_axi_gpio_0_0}]

# IP: bd/zed_base/ip/zed_base_axi_gpio_1_0/zed_base_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_1_0 || ORIG_REF_NAME==zed_base_axi_gpio_1_0}]

# IP: bd/zed_base/ip/zed_base_axi_gpio_2_0/zed_base_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_2_0 || ORIG_REF_NAME==zed_base_axi_gpio_2_0}]

# IP: bd/zed_base/ip/zed_base_processing_system7_0_0/zed_base_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_processing_system7_0_0 || ORIG_REF_NAME==zed_base_processing_system7_0_0}]

# IP: bd/zed_base/ip/zed_base_processing_system7_0_axi_periph_0/zed_base_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zed_base_processing_system7_0_axi_periph_0}]

# IP: bd/zed_base/ip/zed_base_rst_processing_system7_0_50M_0/zed_base_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zed_base_rst_processing_system7_0_50M_0}]

# IP: bd/zed_base/ip/zed_base_xbar_0/zed_base_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_xbar_0 || ORIG_REF_NAME==zed_base_xbar_0}]

# IP: bd/zed_base/ip/zed_base_auto_pc_0/zed_base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_auto_pc_0 || ORIG_REF_NAME==zed_base_auto_pc_0}]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_0_0/zed_base_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_0_0 || ORIG_REF_NAME==zed_base_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_0_0/zed_base_axi_gpio_0_0_ooc.xdc

# XDC: bd/zed_base/ip/zed_base_axi_gpio_0_0/zed_base_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_0_0 || ORIG_REF_NAME==zed_base_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_1_0/zed_base_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_1_0 || ORIG_REF_NAME==zed_base_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_1_0/zed_base_axi_gpio_1_0_ooc.xdc

# XDC: bd/zed_base/ip/zed_base_axi_gpio_1_0/zed_base_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_1_0 || ORIG_REF_NAME==zed_base_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_2_0/zed_base_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_2_0 || ORIG_REF_NAME==zed_base_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_axi_gpio_2_0/zed_base_axi_gpio_2_0_ooc.xdc

# XDC: bd/zed_base/ip/zed_base_axi_gpio_2_0/zed_base_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_axi_gpio_2_0 || ORIG_REF_NAME==zed_base_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/zed_base/ip/zed_base_processing_system7_0_0/zed_base_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zed_base_processing_system7_0_0 || ORIG_REF_NAME==zed_base_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zed_base/ip/zed_base_rst_processing_system7_0_50M_0/zed_base_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zed_base_rst_processing_system7_0_50M_0}]

# XDC: bd/zed_base/ip/zed_base_rst_processing_system7_0_50M_0/zed_base_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_base_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==zed_base_rst_processing_system7_0_50M_0}]

# XDC: bd/zed_base/ip/zed_base_rst_processing_system7_0_50M_0/zed_base_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/zed_base/ip/zed_base_xbar_0/zed_base_xbar_0_ooc.xdc

# XDC: bd/zed_base/ip/zed_base_auto_pc_0/zed_base_auto_pc_0_ooc.xdc

# XDC: bd/zed_base/zed_base_ooc.xdc
